[phases.setup]
nixPkgs = ["python3", "nodejs-18_x"]

[phases.build]
cmds = [
    "npm ci --only=production",
    "cd server && npm ci --only=production",
    "cd client && npm ci && npm run build"
]

[start]
cmd = "cd server && node index.js"