[phases.setup]
nixPkgs = ["python3", "nodejs-18_x", "npm"]

[phases.build]
cmds = [
    "npm install --production",
    "cd server && npm install --production", 
    "cd client && npm install && npm run build"
]

[phases.start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "5000"